//
//  HK_Extensions.swift
//  ActiveRecap
//
//  Created by Nick Morello on 12/14/24.
//

import Foundation
import HealthKit

extension HKWorkoutActivityType {
    var name: String {
        switch self {
        case .americanFootball: return "American Football"
        case .archery: return "Archery"
        case .australianFootball: return "Australian Football"
        case .badminton: return "Badminton"
        case .baseball: return "Baseball"
        case .basketball: return "Basketball"
        case .bowling: return "Bowling"
        case .boxing: return "Boxing"
        case .climbing: return "Climbing"
        case .cricket: return "Cricket"
        case .crossTraining: return "Cross Training"
        case .curling: return "Curling"
        case .cycling: return "Cycling"
        case .dance: return "Dance"
        case .elliptical: return "Elliptical"
        case .equestrianSports: return "Equestrian Sports"
        case .fencing: return "Fencing"
        case .fishing: return "Fishing"
        case .functionalStrengthTraining: return "Functional Strength Training"
        case .golf: return "Golf"
        case .gymnastics: return "Gymnastics"
        case .handball: return "Handball"
        case .hiking: return "Hiking"
        case .hockey: return "Hockey"
        case .hunting: return "Hunting"
        case .lacrosse: return "Lacrosse"
        case .martialArts: return "Martial Arts"
        case .mindAndBody: return "Mind and Body"
        case .paddleSports: return "Paddle Sports"
        case .play: return "Play"
        case .preparationAndRecovery: return "Preparation and Recovery"
        case .racquetball: return "Racquetball"
        case .rowing: return "Rowing"
        case .rugby: return "Rugby"
        case .running: return "Running"
        case .sailing: return "Sailing"
        case .skatingSports: return "Skating Sports"
        case .snowSports: return "Snow Sports"
        case .soccer: return "Soccer"
        case .softball: return "Softball"
        case .squash: return "Squash"
        case .stairClimbing: return "Stair Climbing"
        case .surfingSports: return "Surfing Sports"
        case .swimming: return "Swimming"
        case .tableTennis: return "Table Tennis"
        case .tennis: return "Tennis"
        case .trackAndField: return "Track and Field"
        case .traditionalStrengthTraining: return "Traditional Strength Training"
        case .volleyball: return "Volleyball"
        case .walking: return "Walking"
        case .waterFitness: return "Water Fitness"
        case .waterPolo: return "Water Polo"
        case .waterSports: return "Water Sports"
        case .wrestling: return "Wrestling"
        case .yoga: return "Yoga"
        case .barre: return "Barre"
        case .coreTraining: return "Core Training"
        case .crossCountrySkiing: return "Cross Country Skiing"
        case .downhillSkiing: return "Downhill Skiing"
        case .flexibility: return "Flexibility"
        case .highIntensityIntervalTraining: return "High Intensity Interval Training"
        case .jumpRope: return "Jump Rope"
        case .kickboxing: return "Kickboxing"
        case .pilates: return "Pilates"
        case .snowboarding: return "Snowboarding"
        case .stairs: return "Stairs"
        case .stepTraining: return "Step Training"
        case .wheelchairWalkPace: return "Wheelchair Walk Pace"
        case .wheelchairRunPace: return "Wheelchair Run Pace"
        case .taiChi: return "Tai Chi"
        case .mixedCardio: return "Mixed Cardio"
        case .handCycling: return "Hand Cycling"
        case .discSports: return "Disc Sports"
        case .fitnessGaming: return "Fitness Gaming"
        case .cardioDance: return "Cardio Dance"
        case .socialDance: return "Social Dance"
        case .pickleball: return "Pickleball"
        case .cooldown: return "Cooldown"
        default: return "Other Activity"
        }
    }
    
    var sfSymbol: String {
        switch self {
        case .americanFootball: return "figure.american.football"
        case .archery: return "figure.archery"
        case .badminton: return "figure.badminton"
        case .baseball: return "figure.baseball"
        case .basketball: return "figure.basketball"
        case .bowling: return "figure.bowling"
        case .boxing: return "figure.boxing"
        case .climbing: return "figure.climbing"
        case .cricket: return "figure.cricket"
        case .crossTraining: return "figure.cross.training"
        case .cycling: return "figure.cycling"
        case .dance: return "figure.dance"
        case .elliptical: return "figure.elliptical"
        case .functionalStrengthTraining: return "figure.strengthtraining.functional"
        case .golf: return "figure.golf"
        case .hiking: return "figure.hiking"
        case .hockey: return "figure.hockey"
        case .lacrosse: return "figure.lacrosse"
        case .martialArts: return "figure.martial.arts"
        case .mindAndBody: return "figure.mind.and.body"
        case .pickleball: return "figure.pickleball"
        case .pilates: return "figure.pilates"
        case .play: return "figure.play"
        case .preparationAndRecovery: return "figure.cooldown"
        case .rowing: return "figure.rowing"
        case .rugby: return "figure.rugby"
        case .running: return "figure.run"
        case .sailing: return "figure.sailing"
        case .skatingSports: return "figure.skating"
        case .snowSports: return "figure.skiing"
        case .soccer: return "figure.soccer"
        case .softball: return "figure.softball"
        case .squash: return "figure.squash"
        case .stairClimbing: return "figure.stairs"
        case .surfingSports: return "figure.surfing"
        case .swimming: return "figure.pool.swim"
        case .tableTennis: return "figure.table.tennis"
        case .tennis: return "figure.tennis"
        case .traditionalStrengthTraining: return "figure.strengthtraining.traditional"
        case .volleyball: return "figure.volleyball"
        case .walking: return "figure.walk"
        case .waterFitness: return "figure.water.fitness"
        case .yoga: return "figure.yoga"
        case .barre: return "figure.barre"
        case .coreTraining: return "figure.core.training"
        case .crossCountrySkiing: return "figure.skiing.crosscountry"
        case .downhillSkiing: return "figure.skiing.downhill"
        case .flexibility: return "figure.flexibility"
        case .highIntensityIntervalTraining: return "figure.hiit"
        case .jumpRope: return "figure.jumprope"
        case .kickboxing: return "figure.kickboxing"
        case .snowboarding: return "figure.snowboarding"
        case .stairs: return "figure.stairs"
        case .stepTraining: return "figure.step.training"
        case .wheelchairWalkPace: return "figure.roll.runningpace"
        case .wheelchairRunPace: return "figure.roll.runningpace"
        case .taiChi: return "figure.taichi"
        case .mixedCardio: return "figure.mixed.cardio"
        case .handCycling: return "figure.hand.cycling"
        case .discSports: return "figure.disc.sports"
        case .fitnessGaming: return "figure.gaming"
        case .cardioDance: return "figure.dance"
        case .socialDance: return "figure.dance"
        case .cooldown: return "figure.cooldown"
        default: return "figure.mixed.cardio"
        }
    }
}
